version: '3.7'

services:
  my-backend:
    image: asia.gcr.io/woanso/woanso:5.0
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile.prod

    env_file:
      - ./.env.prod
    ports:
      - 3000:3000
